---
version: 0.6.0
commit: ':bookmark: chore(version): bump to v%.%.%'
files:
  package.json: '"version": "%.%.%"'
  README.md: https://unpkg.com/capsid@%.%.%/dist/capsid.min.js
  docs/README.md: https://unpkg.com/capsid@%.%.%
