---
version: 7.0.0-alpha
commit: Bump to version v%.%.%
files:
  README.md: v%.%.%
  README.ja.md: v%.%.%
  bower.json: '"version": "%.%.%"'
  package.json: '"version": "%.%.%"'
  src/class-component.js: v%.%.%
